//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace kop_launcher.Properties {
	/// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class Resources {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("kop_launcher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.0.0.0.
        /// </summary>
        internal static string DefaultGameVersion {
            get {
                return ResourceManager.GetString("DefaultGameVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://discord.gg/tJvex6E.
        /// </summary>
        internal static string DiscordURL {
            get {
                return ResourceManager.GetString("DiscordURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.facebook.com/kingofpiratesonline.
        /// </summary>
        internal static string FacebookURL {
            get {
                return ResourceManager.GetString("FacebookURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://kingofpirates.net/forum.
        /// </summary>
        internal static string ForumURL {
            get {
                return ResourceManager.GetString("ForumURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.instagram.com/kingofpiratesonline.
        /// </summary>
        internal static string InstagramURL {
            get {
                return ResourceManager.GetString("InstagramURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://kingofpirates.net/game/shop/packages.
        /// </summary>
        internal static string ItemShopPackagesURL {
            get {
                return ResourceManager.GetString("ItemShopPackagesURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://discord.com/api/webhooks/794937615224799252/xO6v3QuPn02SNw1Nx13atSq3P8AkzPde2sZNEPHW5M-dIK9AvXQCG5iufLKOK9VJG8JO.
        /// </summary>
        internal static string LauncherSecurityChannel {
            get {
                return ResourceManager.GetString("LauncherSecurityChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://kingofpirates.net/game/support.
        /// </summary>
        internal static string MailToURL {
            get {
                return ResourceManager.GetString("MailToURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://kingofpirates.net.
        /// </summary>
        internal static string MainWebsiteURL {
            get {
                return ResourceManager.GetString("MainWebsiteURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9BkAxPDlBSDhb13b73HFKFOl915sD.
        /// </summary>
        internal static string StatHashSumDelimiter {
            get {
                return ResourceManager.GetString("StatHashSumDelimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://kingofpirates.net/game/statistics/get.
        /// </summary>
        internal static string StatisticsURL {
            get {
                return ResourceManager.GetString("StatisticsURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://kingofpirates.net/game/client/download/update.xml.
        /// </summary>
        internal static string UpdateXMLFile {
            get {
                return ResourceManager.GetString("UpdateXMLFile", resourceCulture);
            }
        }
    }
}
